### ISSUE TITLE
question about IsWholeNumber() implementation

### ISSUE THREAD

**Issue by Dieterbe** [soudy/mathcat#4]
Hi,
this project looks neat!
I was looking at the code and am a bit puzzled by the IsWholeNumber implementation. it's fascinating.

* can't we just check if `frac == 0` ?
* it's unclear what the significance of `epsilon` is but i assume it's the smallest distinguishable fraction. if that's what it is, how can fraq be smaller than epsilon? if that's not what it is, what is it?
* how about just checking if `n == math.Floor(n)` ?

I have a feeling it's all based on the notion that floats can't be accurately compared but it seems to me my suggestions as well as the current implementation would suffer equally from that.  or i must be missing some important detail..

**Comment by soudy** [comment]
Hi, thanks for the question!
To answer your points:
- can't we just check if frac == 0 ?

No, since floating point math isn't always precise enough ([see here](https://play.golang.org/p/C3A3U4LsuT))

- it's unclear what the significance of epsilon is but i assume it's the smallest distinguishable fraction. if that's what it is, how can fraq be smaller than epsilon? if that's not what it is, what is it?

`epsilon` is there to check the result of `math.Modf(math.Abs(n))` within a small range (0.999999999 through 0.000000001) to try to deal with [float's accuracy problems](https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems).

- how about just checking if n == math.Floor(n) ?

`math.Floor` isn't precise enough (see point 1), [see here](https://play.golang.org/p/fhI4zSXxAc)

This function isn't perfect though, since `IsWholeNumber(2.9999999999999)` still returns true, but it's as good as I could get it.

**Comment by Dieterbe** [comment]
thanks @soudy , i read your response when you wrote it, but forgot to thank you and close this :)

**Comment by soudy** [comment]
@Dieterbe no problem, was just skimming through the issues :)
